#应用服务地址，默认端口是8888，如无特殊设置，不能省略
AppServer = "https://app.wildfirechat.net"
#IM Server的域名
ImServerHost = "wildfirechat.net"
#社区版IM Server时，和ImServerHost是一致的；专业版IM Server时，是集群每个节点配置的节点域名
ImServerNodes = ["node1.wildfirechat.net", "node2.wildfirechat.net", "node3.wildfirechat.net"]
#短链接端口，默认是80，除非特殊定制端口，否则都是80
RoutePort = 80
#长连接端口，默认是1883
LongLinkPort = 1883
# web
EnableWeb = true
#是否启动用wss
UseWSS = true
# UseWSS为false时，默认是80；UseWSS为true时，默认是443
WebRoutePort = 443
# UseWSS为false时，默认是8083；为true时，默认是8084
WsPort = 8084

#备选地址配置
EnableBackupHost = false
BackupImServerHost = "im.wildfirechat.net"
BackupImServerNodes = ["bk1.im.wildfirechat.net"]
BackupRoutePort = 80
BackupLongLinkPort = 1883

# 备选地址是否支持web端
EnableBackupHostWeb = false
BackupUseWSS = false
BackupWebRoutePort = 80
BackupWsPort = 8084
